on:
    workflow_dispatch:

jobs:
    do-the-thing:
        name: test out v5 w secrets
        permissions:
            id-token: write
        runs-on: ubuntu-latest
        steps:
          - name: configure AWS Creds
            uses: aws-actions/configure-aws-credentials@maintux-nn-feat/add-transitive-tag-keys
            with:
                aws-region: us-east-2
                role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                role-duration-seconds: 900
                role-session-name: SecretsManagerFetch
                retry-max-attempts: 6
                transitive-tag-keys: |
                    Repository
                    GitHub
                    Action
